// Package swagger Code generated by swag; DO NOT EDIT.
// To regenerate, run: make swagger
package swagger

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "API Gateway for Go-Micro microservices",
        "title": "Go-Micro Gateway API",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "email": "support@example.com"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "1.0"
    },
    "host": "localhost:8443",
    "basePath": "/",
    "paths": {
        "/api/v1/users": {
            "post": {
                "description": "Create a new user with name and email",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["users"],
                "summary": "Create a new user",
                "parameters": [
                    {
                        "description": "User creation request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/CreateUserRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "User created successfully",
                        "schema": {
                            "allOf": [
                                {"$ref": "#/definitions/SuccessResponse"},
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {"$ref": "#/definitions/UserResponse"}
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Validation error",
                        "schema": {"$ref": "#/definitions/ErrorResponse"}
                    },
                    "409": {
                        "description": "Email already exists",
                        "schema": {"$ref": "#/definitions/ErrorResponse"}
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {"$ref": "#/definitions/ErrorResponse"}
                    }
                }
            }
        },
        "/api/v1/users/{id}": {
            "get": {
                "description": "Retrieve user details by their ID",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["users"],
                "summary": "Get a user by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "User retrieved successfully",
                        "schema": {
                            "allOf": [
                                {"$ref": "#/definitions/SuccessResponse"},
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {"$ref": "#/definitions/UserResponse"}
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Invalid user ID",
                        "schema": {"$ref": "#/definitions/ErrorResponse"}
                    },
                    "404": {
                        "description": "User not found",
                        "schema": {"$ref": "#/definitions/ErrorResponse"}
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {"$ref": "#/definitions/ErrorResponse"}
                    }
                }
            }
        },
        "/api/v1/orders": {
            "post": {
                "description": "Create a new order for a user",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["orders"],
                "summary": "Create a new order",
                "parameters": [
                    {
                        "description": "Order creation request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/CreateOrderRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Order created successfully",
                        "schema": {
                            "allOf": [
                                {"$ref": "#/definitions/SuccessResponse"},
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {"$ref": "#/definitions/OrderResponse"}
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Validation error",
                        "schema": {"$ref": "#/definitions/ErrorResponse"}
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {"$ref": "#/definitions/ErrorResponse"}
                    }
                }
            }
        },
        "/api/v1/orders/{id}": {
            "get": {
                "description": "Retrieve order details by its ID",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["orders"],
                "summary": "Get an order by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Order ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Order retrieved successfully",
                        "schema": {
                            "allOf": [
                                {"$ref": "#/definitions/SuccessResponse"},
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {"$ref": "#/definitions/OrderResponse"}
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Invalid order ID",
                        "schema": {"$ref": "#/definitions/ErrorResponse"}
                    },
                    "404": {
                        "description": "Order not found",
                        "schema": {"$ref": "#/definitions/ErrorResponse"}
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {"$ref": "#/definitions/ErrorResponse"}
                    }
                }
            }
        }
    },
    "definitions": {
        "CreateUserRequest": {
            "type": "object",
            "required": ["name", "email"],
            "properties": {
                "name": {"type": "string", "example": "John Doe"},
                "email": {"type": "string", "example": "john@example.com"}
            }
        },
        "UserResponse": {
            "type": "object",
            "properties": {
                "id": {"type": "integer", "example": 1},
                "name": {"type": "string", "example": "John Doe"},
                "email": {"type": "string", "example": "john@example.com"},
                "created_at": {"type": "string", "example": "2024-01-15T10:30:00Z"}
            }
        },
        "CreateOrderRequest": {
            "type": "object",
            "required": ["user_id", "total"],
            "properties": {
                "user_id": {"type": "integer", "example": 1},
                "total": {"type": "number", "example": 99.99}
            }
        },
        "OrderResponse": {
            "type": "object",
            "properties": {
                "id": {"type": "integer", "example": 1},
                "user_id": {"type": "integer", "example": 1},
                "total": {"type": "number", "example": 99.99},
                "status": {"type": "string", "example": "pending"},
                "created_at": {"type": "string", "example": "2024-01-15T10:30:00Z"}
            }
        },
        "SuccessResponse": {
            "type": "object",
            "properties": {
                "data": {"type": "object"},
                "trace_id": {"type": "string", "example": "550e8400-e29b-41d4-a716-446655440000"}
            }
        },
        "ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {"$ref": "#/definitions/ErrorBody"},
                "trace_id": {"type": "string", "example": "550e8400-e29b-41d4-a716-446655440000"}
            }
        },
        "ErrorBody": {
            "type": "object",
            "properties": {
                "code": {"type": "string", "example": "VALIDATION_ERROR"},
                "message": {"type": "string", "example": "Invalid request body"},
                "details": {"type": "object"}
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8443",
	BasePath:         "/",
	Schemes:          []string{"https", "http"},
	Title:            "Go-Micro Gateway API",
	Description:      "API Gateway for Go-Micro microservices",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
